/**
 * Machine-generated file. Do not modify.
 */

#ifndef _SPECIALCLASSES_H
#define _SPECIALCLASSES_H
#define JAVA_LANG_OBJECT 0
#define JAVA_LANG_THROWABLE 1
#define JAVA_LANG_ERROR 2
#define JAVA_LANG_OUTOFMEMORYERROR 3
#define BOOLEAN 4
#define CHAR 5
#define FLOAT 6
#define DOUBLE 7
#define BYTE 8
#define SHORT 9
#define INT 10
#define LONG 11
#define VOID 12
#define ALJAVA_LANG_OBJECT  13
#define JAVA_LANG_NOSUCHMETHODERROR 14
#define JAVA_LANG_STACKOVERFLOWERROR 15
#define JAVA_LANG_NULLPOINTEREXCEPTION 16
#define AZ 17
#define AC 18
#define AF 19
#define AD 20
#define AB 21
#define AS 22
#define AI 23
#define AJ 24
#define AV 25
#define JAVA_LANG_CLASSCASTEXCEPTION 26
#define JAVA_LANG_ARITHMETICEXCEPTION 27
#define JAVA_LANG_ARRAYINDEXOUTOFBOUNDSEXCEPTION 28
#define JAVA_LANG_ILLEGALARGUMENTEXCEPTION 29
#define JAVA_LANG_INTERRUPTEDEXCEPTION 30
#define JAVA_LANG_ILLEGALSTATEEXCEPTION 31
#define JAVA_LANG_ILLEGALMONITORSTATEEXCEPTION 32
#define JAVA_LANG_THREADDEATH 33
#define JAVA_LANG_ARRAYSTOREEXCEPTION 34
#define JAVA_LANG_NEGATIVEARRAYSIZEEXCEPTION 35
#define JAVA_LANG_CLASS 36
#define JAVA_LANG_STRING 37
#define JAVA_LANG_CLONEABLE 38
#define JAVA_LANG_THREAD 39
#endif // _SPECIALCLASSES_H
