# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_WORLDSTATE_OBJECT = descriptor.Descriptor(
  name='Object',
  full_name='RL.WorldState.Object',
  filename='ML.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pos_x', full_name='RL.WorldState.Object.pos_x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pos_y', full_name='RL.WorldState.Object.pos_y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vel_x', full_name='RL.WorldState.Object.vel_x', index=2,
      number=3, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vel_y', full_name='RL.WorldState.Object.vel_y', index=3,
      number=4, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='angle', full_name='RL.WorldState.Object.angle', index=4,
      number=5, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ang_v', full_name='RL.WorldState.Object.ang_v', index=5,
      number=6, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='left_angle', full_name='RL.WorldState.Object.left_angle', index=6,
      number=7, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_angle', full_name='RL.WorldState.Object.right_angle', index=7,
      number=8, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_WORLDSTATE = descriptor.Descriptor(
  name='WorldState',
  full_name='RL.WorldState',
  filename='ML.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='robot', full_name='RL.WorldState.robot', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ball', full_name='RL.WorldState.ball', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target', full_name='RL.WorldState.target', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_WORLDSTATE.fields_by_name['robot'].message_type = _WORLDSTATE_OBJECT
_WORLDSTATE.fields_by_name['ball'].message_type = _WORLDSTATE_OBJECT
_WORLDSTATE.fields_by_name['target'].message_type = _WORLDSTATE_OBJECT

class WorldState(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Object(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _WORLDSTATE_OBJECT
  DESCRIPTOR = _WORLDSTATE

